### PR TITLE
bootstrap script: Didn't work, works now.

### PR DESCRIPTION
**Pull request by tttttx2**
Updated to match documentation at https://input-output-hk.github.io/jormungandr/stake_pool/registering_stake_pool.html#creating-your-stake-pool-certificate

### CODE REVIEW

**Comment by NicolasDP** [comment]
Are you testing the scripts against a pre-compiled binary?

**Comment by rinor** [comment]
Bootstrap works fine on master and those additional params are necessary. For previous versions please use corresponding version script folder. Ex: for v0.3.3 use [scripts](https://github.com/input-output-hk/jormungandr/tree/v0.3.3/scripts)

**Comment by tttttx2** [comment]
yes, against the latest release. In that case you should maybe add that to the install instructions found here: https://testnet.iohkdev.io/cardano/shelley/get-started/setting-up-the-self-node/ as how it is now you can't get it up and running. But feel free to close it again :)

**Comment by NicolasDP** [comment]
Thanks @tttttx2 and @rinor .

The issue has been redirected to the owner of the testnet.iohkdev.io website.

**Pull request closed without merging**
