### PR TITLE
[Fund8-backport] Add automatic retry + timeout for fetching release (#3895)

### PR DESCRIPTION
**Pull request by Zeegomo**

### CODE REVIEW

**Comment by garbas** [comment]
Maybe we can also use this PR to also backport my nix improvements. Otherwise I can also one a separate PR.

**Comment by Mr-Leshiy** [comment]
@garbas , I would prefer to do it in the separate PR, to not dump all stuff.

**Comment by garbas** [comment]
@Mr-Leshiy ofcourse, I'll create a PR, but this PR will need to be changed as well.

**Comment by Zeegomo** [comment]
superseded by https://github.com/input-output-hk/jormungandr/pull/3905

**Pull request closed without merging**
