### PR TITLE
Rest: settings/stats - update and cleanup

### PR DESCRIPTION
**Pull request by rinor**
Fix https://github.com/input-output-hk/jormungandr/issues/1298

- [x] `maxTxsPerBlock` removed, **settings**
- [x] `blockContentMaxSize` added, **settings**
- [x] `lastBlockContentSize` added, **stats**
- [x] `epochStabilityDepth` added, **settings**

### CODE REVIEW

**Comment by rinor** [comment]
While checking around I saw:
https://github.com/input-output-hk/jormungandr/blob/3339987e04533af745182b4e1aefe78ba239032b/jormungandr/src/rest/v0/handlers.rs#L133-L139
I may be wrong, but why it considers only *normal* tx fragments, ignoring all others ex: Pool op fragments?

**Comment by NicolasDP** [comment]
Sounds like a bug

**Comment by rinor** [comment]
Question: `lastBlockSize` or `lastBlockTxSize` since it will contain Block Content Size (related to `block_content_max_size`)?

**Comment by rinor** [comment]
> Sounds like a bug

Issue filed https://github.com/input-output-hk/jormungandr/issues/1301 and will check later if I can fix that.

**Comment by NicolasDP** [comment]
`lastBlockContentSize` would be better here.

**Comment by rinor** [comment]
Since https://github.com/input-output-hk/jormungandr/pull/1291 was merged I will try to resolve conflicts

**Comment by rinor** [comment]
rebased.

**Pull request merged**
