### PR TITLE
jormungandr-testing-utils: add QR code generator

### PR DESCRIPTION
**Pull request by mzabaluev**
The encode part for #2811.

### CODE REVIEW

**Comment by dkijania** [comment]
Working good. was able to scan qr using catalyst app

**Review by dkijania — APPROVED** [review]

**Comment by enzoc4** [comment]
shouldn't we use the same code that's in `chain-wallet-libs`? The [encryption](https://github.com/input-output-hk/chain-wallet-libs/blob/47bca1e53f93351514c132db950ceb291c3fdf64/symmetric-cipher/src/lib.rs#L32) and [decryption](https://github.com/input-output-hk/chain-wallet-libs/blob/47bca1e53f93351514c132db950ceb291c3fdf64/symmetric-cipher/src/lib.rs#L88) functions that are used for voting are already written in rust, so unless the purpose is to explicitly double check the implementation it seems like we should reuse that part.

**Comment by dkijania** [comment]
@enzoc4 thanks for being watchful. I didn't realize that there is already a method in rust for this (now it's obvious that there should be one).  Yes, we should use as much `chain-wallet-lib` code as possible.

**Comment by eugene-babichenko** [comment]
@darek have you tested it after Enzo's change?

**Comment by dkijania** [comment]
will test it today or tommorow

**Comment by dkijania** [comment]
working good. Thanks @mzabaluev and @enzoc4

**Pull request merged**
