### PR TITLE
[Tests] Rewards dump soak test

### PR DESCRIPTION
**Pull request by dkijania**
Created single test which uses auto dumping rewards statistics for each epoch.

### CODE REVIEW

**Comment by NicolasDP** [comment]
what's up with this PR @dkijania ?

**Comment by dkijania** [comment]
It Reproduces issue #1933 which is still open

**Comment by NicolasDP** [comment]
don't use the reward dump directory, there is a rest API, thereward dump is going to disapear in a few weeks

**Comment by NicolasDP** [comment]
@dkijania CI is failing on the fmt

**Pull request merged**
