### PR TITLE
update all dependencies to use cryptoxide 0.3.1

### PR DESCRIPTION
**Pull request by eugene-babichenko**
this prevents compilation errors with future versions of rustc

### CODE REVIEW

**Comment by Zeegomo** [comment]
I'm a little confused on what happens if the version in Cargo.lock is more recent than the version in Cargo.toml (chain-crypto is on 0.2.1)? I think this should be handled by updating the version used in dependencies,  since it's not used directly in jormungandr.

 Or was this a temporary fix?

**Comment by eugene-babichenko** [comment]
IIRC `cargo update` automatically decides on updates compatibility based on semver numbers if you do not specify more strict constraints along with the version number.

**Comment by eugene-babichenko** [comment]
But that dependency in chain-libs still needs an update.

**Review by Zeegomo — APPROVED** [review]
It looks like I was wrong, the only dependency that still used < 0.3 cryptoxide was symmetric-cipher, that you updated as well in this pr. Good to go then!

**Pull request merged**
