### PR TITLE
Create sender app for fetching node stats over HTTP

### PR DESCRIPTION
**Pull request by CodeSandwich**

### CODE REVIEW

**Comment by NicolasDP** [comment]
What does it look like on the CLI ? can you add an example ?

**Comment by CodeSandwich** [comment]
@NicolasDP I've added a manual to readme

**Comment by NicolasDP** [comment]
you might need to rebase the branch to latest jormungrandr. the tower-grpc issue is fixed now.

**Comment by CodeSandwich** [comment]
@NicolasDP Done :)

**Pull request merged**
