### PR TITLE
ci/release: remove unnecessary checkout

### PR DESCRIPTION
**Pull request by eugene-babichenko**

### CODE REVIEW

**Comment by eugene-babichenko** [comment]
@danielSanchezQ Is it safe to have a single "Publish release" workflow instead of two separate workflows? Same question for nightly also.

**Comment by danielSanchezQ** [comment]
@eugene-babichenko you mean to merge both nightly and release ones?

**Comment by eugene-babichenko** [comment]
@danielSanchezQ No. In `release.yml` there are two jobs: `initial_release` and `release_assets`. Can we make just a single `release` job which creates a release (the `Create Release` step) and then performs a build and uploads assets?

**Comment by danielSanchezQ** [comment]
No, I don't think we can. The reason is that the second one is a matrix, so the release will be remake for each target then.

**Comment by eugene-babichenko** [comment]
Ah, thanks, got it.

**Pull request merged**
