### PR TITLE
integrate fix for DatabaseLocked error

### LINKED ISSUE #1638: DatabaseLocked error when using in-memory database
This log line appears when using sqlite in-memory mode.

```
[INFO ][Leader2@127.0.0.1:8001]: Jan 23 11:44:47.004 INFO validation of an incoming block failed, reason: Error(Storage(BackendError(SqliteFailure(Error { code: DatabaseLocked, extended_code: 262 }, Some("database table is locked: BlockInfo")))), State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }), task: block
```

### PR DESCRIPTION
**Pull request by eugene-babichenko**
fix #1638 and integrate https://github.com/input-output-hk/chain-libs/pull/245

### CODE REVIEW

**Comment by mzabaluev** [comment]
A PR integrating unmerged branches in chain-deps should be opened as a draft.
Once the dependent changes are merged to master, this can be rebased and updated.

**Comment by dkijania** [comment]
@eugene-babichenko can you rebase on newest master ? there were changes in rest api (regarding node stats).

**Comment by dkijania** [comment]
ok. managed to run tests against this PR. For me it looks good. No issues connected with `DatabaseLocked`

**Comment by eugene-babichenko** [comment]
@dkijania I rebased it onto `master`. Also I added potentially more stable `unlock_notify` feature instead of using `read_uncommitted`. For me tests are good. Can you try it once again just to make sure everything is good?

**Comment by dkijania** [comment]
@eugene-babichenko Tests finished. looks good.

**Pull request merged**
