### PR TITLE
[Tests] increase default slot duration in tests to 2 secs

### PR DESCRIPTION
**Pull request by Zeegomo**
CircleCI is a bit slow and this can cause forking inside a single node.
Let's try to increase the default slot time to 2s and hope this fixes the problem without increasing test times too much

### CODE REVIEW

**Comment by dkijania** [comment]
Looking good. Sorry for explicitly setting slot_duration in so many tests...

**Comment by Zeegomo** [comment]
Mmm, this is now too slow for GitHub. Maybe we can indeed put writing to storage in a separate background task

**Comment by dkijania** [comment]
In my PR https://github.com/input-output-hk/jormungandr/pull/3600 I've extended timeout for github action tests. Maybe it's acceptable solution?

**Review by mzabaluev — APPROVED** [review]
Looks good to me, especially as it deduplicates TTL setup in most cases.

**Review by eugene-babichenko — APPROVED** [review]

**Pull request merged**
