### PR TITLE
Update README: add instructions to build

### PR DESCRIPTION
**Pull request by NicolasDP**
add instructions to build jormungandr from sources.

### CODE REVIEW

**Comment by dorin100** [comment]
@NicolasDP - I was able to do the first 2 steps but I cannot install 'cargo'

D:\iohk\otherProjects\jormungandr>cargo install
'cargo' is not recognized as an internal or external command,
operable program or batch file.

**Comment by dorin100** [comment]
ok. so on windows it seems that I need to add the /userProfile/.cargo/bin into the Path and then the 'cargo install' will work if executed from the jormungandr root

**Comment by NicolasDP** [comment]
thanks, I'll add this in the README

**Comment by dorin100** [comment]
I installed Cargo and I also created the genessis.yaml file. Now I am at the Node Configuration part and it is not clear where this node config is stored... Where is this file located? Or should I create it - if yes, what kind of file/extension should it have?

**Pull request merged**
