### PR TITLE
Update chain-libs for parallel spending

### PR DESCRIPTION
**Pull request by mzabaluev**
Initial adaptation for chain-impl-mockchain API changes for independent
spending counters lanes.
Also tonic and prost versions were updated.

### CODE REVIEW

**Review by Zeegomo — COMMENTED** [review]
I think we should update the changelog here, apart from that LGTM.

There is no way to use lanes other than 0 with jcli, which is not a big issue actually. We should update testing functions at least to be able to stress other lanes, but it can be done in another PR.

Also, I've just realized that this change adds explicit spending counter in the transaction. There were some proposals for improvements if this was known, with the simplest one being better diagnostic errors.

**Comment by mzabaluev** [comment]
> There is no way to use lanes other than 0 with jcli, which is not a big issue actually.

An option could be added to jcli fragment creation commands, but it can be done in a separate PR.

**Review by Zeegomo — APPROVED** [review]

**Comment by Zeegomo** [comment]
> There is no way to use lanes other than 0 with jcli, which is not a big issue.
You actually can, albeit with a kind of obscure interface. The spending counter is provided in the witness as a `u32`, and a conversion between `u32` and `SpendingCounter` is well defined and takes lanes into account in the first bits. I think it may be sufficient for now

**Review by vincenthz — APPROVED** [review]

**Comment by Zeegomo** [comment]
Will hold this off until after the feature freeze not to bring additional load on the app side

**Comment by Mr-Leshiy** [comment]
@Zeegomo As we have merged it into the chain-libs side, I assume we can merge this PR into master too. But create two new branches related to the fund7 without this feature and deploy them.

**Pull request merged**
