### PR TITLE
Fix REST API docs

### PR DESCRIPTION
**Pull request by GaborPeto**
❌`./jcli rest v0 stake_pools get --host http://127.0.0.1:3101/api`
✅ `./jcli rest v0 stake-pools get --host http://127.0.0.1:3101/api`

### CODE REVIEW

**Comment by NicolasDP** [comment]
Thanks @CodeSandwich

**Comment by NicolasDP** [comment]
Screenshot 2019-10-15 at 09 43 08

well actually...

**Comment by GaborPeto** [comment]
:'(

**Comment by CodeSandwich** [comment]
@NicolasDP URLs and JCLI commands follow different conventions. This is PR fixing the OpenAPI file, so the raw URL docs. Run this command with `--debug` and see what is sent under the hood.

**Comment by NicolasDP** [comment]
ho I see, the issue reported is not the issue changed.

**Pull request closed without merging**
